<?php

?>
	<footer class="footer">
		<div class="footer__wrap baseInContainer">

			<div class="menu-bottom footer__menu">
				<div class="menu-bottom__col">
					<div class="menu-bottom__title">Информация</div>
					<ul class="menu-bottom__ul">
						<li class="menu-bottom__li">
							<a href="/company" class="menu-bottom__link">О компании</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/blog" class="menu-bottom__link">Новости</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/compatible-devices" class="menu-bottom__link">Совместимые устройства</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/press-service" class="menu-bottom__link">Пресс-служба</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/contact" class="menu-bottom__link">Контакты</a>
						</li>
					</ul>
				</div>
				<div class="menu-bottom__col">
					<div class="menu-bottom__title">Партнёрам</div>
					<ul class="menu-bottom__ul">
						<li class="menu-bottom__li">
							<a href="/partner" class="menu-bottom__link">Сотрудничество</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/partners" class="menu-bottom__link">Партнёры</a>
						</li>
					</ul>
				</div>
				<div class="menu-bottom__col">
					<div class="menu-bottom__title">Поддержка</div>
					<ul class="menu-bottom__ul">
						<li class="menu-bottom__li">
							<a href="/help" class="menu-bottom__link">Помощь</a>
						</li>
						<li class="menu-bottom__li menu-bottom__li_phone">
							<a href="tel:+78007775373" class="menu-bottom__link">8 800 777-53-73</a>
						</li>
						<li class="menu-bottom__li menu-bottom__li_email">
							<a href="mailto:support@rubetek.com" class="menu-bottom__link">support@rubetek.com</a>
						</li>
					</ul>
				</div>
				<div class="menu-bottom__col">
					<div class="menu-bottom__title">Сервис</div>
					<ul class="menu-bottom__ul">
						<li class="menu-bottom__li">
							<a href="/order-setup" class="menu-bottom__link">Заказать установку</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/warranty" class="menu-bottom__link">Гарантия и возврат</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/delivery" class="menu-bottom__link">Доставка</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/shops" class="menu-bottom__link">Магазины</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/service" class="menu-bottom__link">Сервисные центры</a>
						</li>
						<li class="menu-bottom__li">
							<a href="/installers" class="menu-bottom__link">Инсталляторы</a>
						</li>
					</ul>
				</div>
			</div>

			<div class="footer__contact">
				<div class="footer__col footer__col_social">

					<div class="social-icon">
						<a href="https://www.facebook.com/rubetek/" target="_blank" class="social-icon__link social-icon__link_fb" onClick="ga('send', 'event', 'SocialMedia', 'FB');"></a>
						<a href="https://vk.com/rubetek_com" target="_blank" class="social-icon__link social-icon__link_vk" onClick="ga('send', 'event', 'SocialMedia', 'VK');"></a>
						<a href="https://ok.ru/group/53387312758868" target="_blank" class="social-icon__link social-icon__link_ok" onClick="ga('send', 'event', 'SocialMedia', 'OK')"></a>
						<a href="https://twitter.com/Rubetek_com" target="_blank" class="social-icon__link social-icon__link_tw" onClick="ga('send', 'event', 'SocialMedia', 'TW');"></a>
						<a href="https://www.instagram.com/rubetek_com/" target="_blank" class="social-icon__link social-icon__link_in" onClick="ga('send', 'event', 'SocialMedia', 'INSTA');"></a>
						<a href="https://www.youtube.com/channel/UC2fOTXEd32svyFbtqft1rdA" target="_blank" class="social-icon__link social-icon__link_youtube" onClick="ga('send', 'event', 'SocialMedia', 'INSTA');"></a>

					</div>

				</div>
				<div class="footer__col footer__col_app">

					<div class="app">
						<a href="https://itunes.apple.com/ru/app/rubetek/id798738097" target="_blank" class="app__link app__link_app-store"></a>
						<a href="https://play.google.com/store/apps/details?id=com.rubetek.client" target="_blank" class="app__link app__link_google-play"></a>
					</div>

				</div>
			</div>
			<div class="footer-bottom">
				<div class="footer-bottom__item">© 2017 Rubetek</div>
				<div class="footer-bottom__item">
					<a href="/confidentiality" class="footer-bottom__link">Конфиденциальность</a>
				</div>
				<div class="footer-bottom__item">
					<a target="_blank" href="/data/rules-of-using.pdf" class="footer-bottom__link">Условия использования</a>
				</div>
				<div class="footer-bottom__item">
					<a target="_blank" href="/data/contract-offert.pdf" class="footer-bottom__link">Договор-оферта</a>
				</div>
			</div>
		</div>
	</footer>