<?php

?>
	<header class="header" itemscope="" itemtype="http://schema.org/WPHeader">

		<div class="header-topPanel baseInContainer">

			<a href="/" class="header-topPanelLogo"></a>

			<div class="header-topPanelList">
				<div class="header-topPanelListElement">
					<a href="/products" class="header-topPanelListElementLink">Каталог</a>
				</div>

				<div class="header-topPanelListElement header-howItWorks">
					<a href="/how-it-works" class="header-topPanelListElementLink">Как это работает</a>
				</div>

				<div class="header-topPanelListElement header-linkShops">
					<a href="/shops" class="header-topPanelListElementLink">Магазины</a>
				</div>

				<div class="header-topPanelListElement header-linkDelivery">
					<a href="/delivery" class="header-topPanelListElementLink">Доставка</a>
				</div>

				
				<div class="header-topPanelListElement header-linkBlog">
					<a href="/blog" class="header-topPanelListElementLink">Новости</a>
				</div>

				<div class="header__new-year-ball"></div>
			</div>

			<div class="header-topPanelBasket">
				<div class="header-topPanelBasketElement">
					<a href="cart.html" class="header-topPanelBasketElementLink">
						<i class="header-topPanelBasketElementLinkIcon cartIconWhite"></i>
						Корзина
						<span class="header-topPanelBasketElementLinkCount linkCountNone">0</span>
					</a>
				</div>
			</div>

			<div class="header-topPanelAuth ">
								<div class="header-topPanelAuthElement">
						<a href="index.html#login" class="header-topPanelAuthElementLink" onclick="Rubetek.openAuthPopup(); return false;">Вход</a>
					</div>

					<div class="header-topPanelAuthElement">
						<a href="index.html#registration" class="header-topPanelAuthElementLink" onclick="Rubetek.openRegistrationPopup()">Регистрация</a>
					</div>
						</div>

			<div class="header-topPanelPhone">
				<a class="header-topPanelPhoneLink" href="tel:+78007775373">8 800 777-53-73</a>
			</div>

			<div class="header-topPanelMobileMenu">
				<img src="/images/ico/menu_icon.png" class="header-topPanelMobileMenuIcon" onclick="Rubetek.showMobileMenu()">
			</div>


		</div>
	</header>